### ISSUE TITLE
ed25519 support?

### ISSUE THREAD

**Issue by chulkilee** [buildkite/docker-ssh-env-config#4]
For example now github recommends ed25519 format - https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by gtzo-anchorage** [comment]
+1

**Comment by mbarrien** [comment]
FYI, in practice, I've found that you can provide an ed25519 formatted key as the SSH_PRIVATE_RSA_KEY environment variable, and it will still work.
